// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace EntityFrameworkLibrary.Models;

public partial class DateFormats
{
    public int? dateFormatOption { get; set; }

    public string dateOutput { get; set; }
}