// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace EntityFrameworkLibrary.Models;

public partial class Events
{
    public int EventID { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }
}