// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace EntityFrameworkLibrary.Models;

public partial class Movies
{
    public int Id { get; set; }

    public TimeOnly? Duration { get; set; }

    public string Title { get; set; }
}