// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EntityFrameworkLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace EntityFrameworkLibrary.Data.Configurations
{
    public partial class RoomConfiguration : IEntityTypeConfiguration<Room>
    {
        public void Configure(EntityTypeBuilder<Room> entity)
        {
            entity.HasKey(e => e.RoomIdentifier);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Room> entity);
    }
}
