// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;


namespace EntityFrameworkLibrary.Data
{
    public partial class Context
    {

        [DbFunction("udf_AddBusinessDays", "dbo")]
        public static DateTime? udf_AddBusinessDays(DateTime? Date, int? BusinessDays)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
